stages:
  - build

variables:
  ARCHIVE_NAME: geonkick

before_script:
  - apt-get update -qy
  - apt-get install -y git build-essential cmake libjack-dev libsndfile-dev rapidjson-dev lv2-dev libcairo2-dev
  - apt-get install -y libx11-xcb-dev libxcb-util-dev libxcb-cursor-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libfontconfig1-dev libcairo2-dev libgtkmm-3.0-dev libsqlite3-dev libxcb-keysyms1-dev

build:
  stage: build
  script:
    - mkdir -p build/install
    - git clone --recursive https://github.com/steinbergmedia/vst3sdk.git
    - VST3SDKPATH=$(pwd)/vst3sdk
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=./install -DVST3_SDK_PATH=$VST3SDKPATH ..
    - make -j 4
    - make install
    - tar czf "${ARCHIVE_NAME}.tar.gz" install
    - tar cjf "${ARCHIVE_NAME}.tar.bz2" install
  artifacts:
    paths:
      - build/${ARCHIVE_NAME}.tar.gz
      - build/${ARCHIVE_NAME}.tar.bz2
  only:
    - main
    - tags
