stages:
  - build

build:
  stage: build
  script:
    - apt-get update -qy
    - apt-get install -y build-essential cmake libjack-dev libsndfile-dev libssl-dev rapidjson-dev lv2-dev libcairo2-dev
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/src/standalone/geonkick
  only:
    - version3
