stages:
  - build

variables:
  ARCHIVE_NAME: geonkick
  ARTIFACTS_PATH: GNU/Linux (LV2 & Standalone)

before_script:
  - apt-get update -qy
  - apt-get install -y build-essential cmake libjack-dev libsndfile-dev libssl-dev rapidjson-dev lv2-dev libcairo2-dev

build:
  stage: build
  script:
    - mkdir -p build/install
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=./install ..
    - make
    - make install
    - tar czf "${ARCHIVE_NAME}.tar.gz" install
    - tar cjf "${ARCHIVE_NAME}.tar.bz2" install
  artifacts:
    paths:
      - ${ARTIFACTS_PATH}/${ARCHIVE_NAME}.tar.gz
      - ${ARTIFACTS_PATH}/${ARCHIVE_NAME}.tar.bz2
  only:
    - main
