.\" Manpage for geonkick.
.\" Author: Iurie Nistor
.\" License: this manpage is released under CC0 1.0 Universal (CC0 1.0) Public Domain Dedication.
.\" Contact iuriehn@gmail.com to correct errors or typos.
.TH man 1 "18 August 2020" "1.0" "geonkick man page"
.SH NAME
geonkick \- a percussion synthesizer.
.SH SYNOPSIS
geonkick <preset file>
.SH DESCRIPTION
geonkick is a synthesizer that can synthesize elements of percussion.
.SH OPTIONS
geonkick doesn't any take options.
.SH EXAMPLES

geonkick /path/to/preset.gkick

.SH LICENSE

geonkick is Free Software released under GPLv3.

.SH AUTHOR
Iurie Nistor <iuriehn@gmail.com>
