name: GNU/Linux (LV2, VST3, Standalone)

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ARCHIVE_NAME: [geonkick]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up build environment
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y git build-essential cmake libjack-dev libsndfile-dev rapidjson-dev lv2-dev libcairo2-dev

      - name: Build
        run: |
          mkdir -p build/install
          git clone --recursive https://github.com/steinbergmedia/vst3sdk.git
          VST3SDKPATH=$(pwd)/vst3sdk
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=./install -DVST3_SDK_PATH=$VST3SDKPATH ..
          make -j 4
          make install
          tar czf "${{ matrix.ARCHIVE_NAME }}.tar.gz" install
          tar cjf "${{ matrix.ARCHIVE_NAME }}.tar.bz2" install

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.ARCHIVE_NAME }}-artifacts
          path: |
            build/${{ matrix.ARCHIVE_NAME }}.tar.gz
            build/${{ matrix.ARCHIVE_NAME }}.tar.bz2
