name: Windows (VST3)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
 
      - name: Building 
        run: |
          pacman -S --noconfirm git mingw-w64-ucrt-x86_64-toolchain mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-libsndfile mingw-w64-ucrt-x86_64-openssl mingw-w64-ucrt-x86_64-rapidjson mingw-w64-ucrt-x86_64-cairo make
          git clone https://github.com/Geonkick-Synthesizer/geonkick.git
          git clone --recursive https://github.com/steinbergmedia/vst3sdk.git
          mkdir -p /d/a/geonkick/build
          cd /d/a/geonkick/build
          cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=./install -DVST3_SDK_PATH=/d/a/geonkick/geonkick/vst3sdk -DSMTG_ENABLE_VST3_PLUGIN_EXAMPLES=OFF -DSMTG_ENABLE_VST3_HOSTING_EXAMPLES=OFF -DSMTG_ENABLE_VSTGUI_SUPPORT=OFF /d/a/geonkick/geonkick/geonkick
          sed -i 's/std:://g' /d/a/geonkick/geonkick/vst3sdk/public.sdk/source/vst/utility/alignedalloc.h
          make VERBOSE=1
          mkdir -p Geonkick.vst3/Contents/x86-win
          cp -fr /d/a/geonkick/build/src/plugin/vst/Geonkick.dll  /d/a/geonkick/build/Geonkick.vst3/Contents/x86-win/Geonkick.vst3
          ls -l /d/a/geonkick/build/

      - name: Create Tarball
        run: |
          tar -czvf /d/a/geonkick/build/Geonkick.vst3.tar.gz -C /d/a/geonkick/build/ Geonkick.vst3
          ls -l /d/a/geonkick/build/
          ls /d/a/_temp/msys64/home

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: geonkick-artifacts
          path: /d/a/geonkick/build/Geonkick.vst3.tar.gz
